---
- hosts: all
  vars:
    cnf: true
    vnf: false
    # Run host vSwitch in container
    vswitch_container: false
    nic_type: "intel"
    multus_cni: false
    baseline: false
    hugepages: 10240
    isolated_cores: "{{ lookup('env', 'ISOLATED_CORES') }}"
    corelist_workers: 3
    rx_queues: 3
    config_network_bonds: true
    config_network_bridges: false
    config_network_interfaces: true
    enable_configured_interfaces_after_defining: true
    # Never build from source here
    vpp_src: false
    nic_port2: "{{ ansible_eno2.pciid }}"
    nic_port3: "{{ ansible_eno3.pciid }}"
    dns_nameservers:
      - "{{ ansible_dns.nameservers[0] }}"
      - "{{ ansible_dns.nameservers[1] }}"
  pre_tasks:
  - name: Apt update
    apt:
      update_cache: yes
  - name: Install Vlan Package
    apt: 
      name: vlan
  - name: Install pip
    apt:
      name: python-pip
    when: vswitch_container
  - name: Install docker-py
    pip:
      name: docker-py
    when: vswitch_container
  post_tasks:
  - name: Reboot Server
    reboot:
  roles:
# - grub_update
    - { role: "vpp_install", when: not vswitch_container }
    - { role: "vpp_container_install", when: vswitch_container }
    - vpp_config
